### ISSUE TITLE
Summary shouldn't end with a period

### ISSUE THREAD

**Issue by razzeee** [flathub/io.gitlab.gwendalj.package-transporter#1] opened 2023-08-30 18:06 UTC
See https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#no-weird-formatting-1

**Comment by knacky34** [comment] 2023-08-31 10:13
The issue is fixed in version 0.1.1.
See [PR](https://github.com/flathub/io.gitlab.gwendalj.package-transporter/pull/2)

**Closed as completed** 2023-08-31 10:13 UTC
